replicaCount: 2

image:
  repository: webapp1
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  WEBAPP2_BASE_URL: "http://webapp2.webapp2.svc.cluster.local"

ingress:
  enabled: false

resources: {}

probes:
  startup:
    enabled: true
    path: /health
    periodSeconds: 2
    failureThreshold: 30
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 6
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
